#define TIC_VERSION_MAJOR       1
#define TIC_VERSION_MINOR       2
#define TIC_VERSION_REVISION    3090
#define TIC_VERSION_STATUS      "-dev"
#define TIC_VERSION_IS_RELEASE  0
#define TIC_VERSION_TAG         "v1.2.0"
#define TIC_VERSION_BUILD       ""
#define TIC_VERSION_YEAR        "2026"
#define TIC_VERSION_HASH        "7ac4f63"
