#ifndef LILY_TIC80_BINDINGS_H
#define LILY_TIC80_BINDINGS_H
/* NOT Generated by lily-bindgen, EDIT AS YOU SEE FIT. */

#if defined(_WIN32) && !defined(LILY_NO_EXPORT)
#define LILY_TIC80_EXPORT __declspec(dllexport)
#else
#define LILY_TIC80_EXPORT
#endif

LILY_TIC80_EXPORT
const char *lily_tic80_info_table[] = {
    "\0\0"
    ,"F\0cls\0(Integer)"
    ,"Z"
};
#define LILY_DECLARE_TIC80_CALL_TABLE \
LILY_TIC80_EXPORT \
lily_call_entry_func lily_tic80_call_table[] = { \
    NULL, \
    lily_tic80__cls, \
};
#endif
